# Dev test config

AppPager = "./pkg/courier"

KeyLeft = "h"
KeyDown = "j"
KeyUp = "k"
KeyRight = "l"
KeyQuit = "q"
KeyCmdmode = ":"
KeyCmdenter = "\r"

CmdlinePrefix = ":"
FeedbackPrefix = "<"

[HeaderFg]
Active = false
R = 230
G = 230
B = 230

[HeaderBg]
Active = false
R = 20
G = 50
B = 20

[TitleFg]
Active = false
R = 230
G = 230
B = 230

[TitleBg]
Active = false
R = 20
G = 50
B = 50

[FeedbackFg]
Active = true
R = 175
G = 175
B = 175

[FeedbackBg]
Active = false
R = 0
G = 0
B = 0

[CmdlineFg]
Active = false
R = 200
G = 255
B = 200

[CmdlineBg]
Active = false
R = 20
G = 20
B = 20
