# Dev test config

[Pager]
Name = "./pkg/courier"

[Keys]
Left = "h"
Down = "j"
Up = "k"
Right = "l"
Quit = "q"
Cmdmode = ":"
Cmdenter = "\r"

[Header]
Alignment = "right"

[Header.Fg]
Active = false
R = 230
G = 230
B = 230

[Header.Bg]
Active = false
R = 20
G = 50
B = 20

[Title]
Alignment = "left"

[Title.Fg]
Active = false
R = 230
G = 230
B = 230

[Title.Bg]
Active = false
R = 20
G = 50
B = 50

[CmdLine]
Alignment = "left"
Prefix = ":"

[CmdLine.Fg]
Active = false
R = 200
G = 255
B = 200

[CmdLine.Bg]
Active = false
R = 20
G = 20
B = 20

[Feedback]
Alignment = "center"
Prefix = "<"

[Feedback.Fg]
Active = true
R = 175
G = 175
B = 175

[Feedback.Bg]
Active = false
R = 0
G = 0
B = 0
