# Dev test config

Header = "Dev courier test\n"
PagerTitle = 'Courier - Feedback'

ContentAlignment = "center"

GoStart = 'Welcome'
GoQuit = 'Goodbye'

[ContentFg]
Active = false
R = 0
G = 0
B = 0

[ContentBg]
Active = false
R = 0
G = 0
B = 0
