# Dev test config

Header = "Dev courier test\n"

[Pager]
Title = 'Courier - Feedback'

[Content]
Alignment = "center"

[Content.Fg]
Active = false
R = 0
G = 0
B = 0

[Content.Bg]
Active = false
R = 0
G = 0
B = 0

[Events]
Start = 'Welcome'
Quit = 'Goodbye'
