# Dev test config

KeyExecute = "L"

EntryMenuPrefix = "> ["
EntryMenuPostfix = "]"
EntryShellPrefix = "> "
EntryShellPostfix = ""
EntryShellSessionPrefix = "> <"
EntryShellSessionPostfix = ">"

EntryAlignment = "center"

Header = "Example hui\n"

[EntryFg]
Active = false
R = 0
G = 0
B = 0

[EntryBg]
Active = false
R = 0
G = 0
B = 0

[EntryHoverFg]
Active = true
R = 0
G = 0
B = 0

[EntryHoverBg]
Active = true
R = 255
G = 255
B = 255

[Menus]
[Menus.main]
Title = "Main Menu\n---------"

[[Menus.main.Entries]]
Caption = 'echo to temp'
Shell = 'echo gotest >> ~/temp'

[[Menus.main.Entries]]
Caption = 'Submenu'
Menu = 'submenu'

[Menus.submenu]
Title = "Submenu\n-------"

[[Menus.submenu.Entries]]
Caption = 'vi ~/temp.md'
ShellSession = 'vi ~/temp.md'

[[Menus.submenu.Entries]]
Caption = 'neofetch (glitchy)'
Shell = 'neofetch'

[[Menus.submenu.Entries]]
Caption = 'neofetch without icon or col blocks'
Shell = 'neofetch --off --color_blocks off'

[[Menus.submenu.Entries]]
Caption = 'print short'
Shell = 'echo short'

[[Menus.submenu.Entries]]
Caption = 'print long'
Shell = 'echo loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong'

[[Menus.submenu.Entries]]
Caption = 'print too long'
Shell = 'echo looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong'
