KeyLeft = "h"
KeyDown = "j"
KeyUp = "k"
KeyRight = "l"
KeyExecute = "L"
KeyQuit = "q"
KeyCmdmode = ":"
KeyCmdenter = "\r"

CmdlinePrefix = ":"
FeedbackPrefix = "<"
EntryMenuPrefix = "> ["
EntryMenuPostfix = "]"
EntryShellPrefix = "> "
EntryShellPostfix = ""
EntryShellSessionPrefix = "> <"
EntryShellSessionPostfix = ">"
Header = "Example config\n"

[HeaderFg]
Active = false
R = 0
G = 0
B = 0

[HeaderBg]
Active = false
R = 0
G = 0
B = 0

[TitleFg]
Active = false
R = 0
G = 0
B = 0

[TitleBg]
Active = false
R = 0
G = 0
B = 0

[EntryFg]
Active = false
R = 0
G = 0
B = 0

[EntryBg]
Active = false
R = 0
G = 0
B = 0

[EntryHoverFg]
Active = true
R = 0
G = 0
B = 0

[EntryHoverBg]
Active = true
R = 255
G = 255
B = 255

[FeedbackFg]
Active = true
R = 175
G = 175
B = 175

[FeedbackBg]
Active = false
R = 0
G = 0
B = 0

[CmdlineFg]
Active = false
R = 0
G = 0
B = 0

[CmdlineBg]
Active = false
R = 0
G = 0
B = 0

[Menus]
[Menus.main]
Title = "Main Menu\n---------"

[[Menus.main.Entries]]
Caption = 'echo to temp'
Shell = 'echo gotest >> ~/temp'

[[Menus.main.Entries]]
Caption = 'Submenu'
Menu = 'submenu'

[Menus.submenu]
Title = 'Submenu'

[[Menus.submenu.Entries]]
Caption = 'vi ~/temp.md'
ShellSession = 'vi ~/temp.md'

[[Menus.submenu.Entries]]
Caption = 'print short'
Shell = 'echo short'

[[Menus.submenu.Entries]]
Caption = 'print long'
Shell = 'echo loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong'

[[Menus.submenu.Entries]]
Caption = 'print too long'
Shell = 'echo looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong'
