[Pager]
Fallback = "courier"

[Keys]
Left = "h"
Down = "j"
Up = "k"
Right = "l"
Quit = "q"
Cmdmode = ":"
Cmdenter = "\r"

[Header]
Alignment = "center"

[Header.Fg]
Active = true
R = 100
G = 255
B = 100

[Header.Bg]
Active = false
R = 0
G = 0
B = 0

[Title]
Alignment = "left"

[Title.Fg]
Active = true
R = 200
G = 255
B = 200

[Title.Bg]
Active = false
R = 0
G = 0
B = 0

[CmdLine]
Alignment = "left"
Prefix = ":"

[CmdLine.Fg]
Active = true
R = 175
G = 175
B = 255

[CmdLine.Bg]
Active = false
R = 0
G = 0
B = 0

[Feedback]
Alignment = "left"
Prefix = "<"

[Feedback.Fg]
Active = true
R = 175
G = 175
B = 175

[Feedback.Bg]
Active = false
R = 0
G = 0
B = 0
