Header = "Courier - Demo Config\n"
PagerTitle = 'Courier - Feedback'

ContentAlignment = "left"

GoStart = ''
GoQuit = ''

[ContentFg]
Active = false
R = 0
G = 0
B = 0

[ContentBg]
Active = false
R = 0
G = 0
B = 0
