Header = "Courier - Demo Config\n"

[Pager]
Title = 'Courier - Feedback'

[Content]
Alignment = "left"

[Content.Fg]
Active = false
R = 0
G = 0
B = 0

[Content.Bg]
Active = false
R = 0
G = 0
B = 0

[Events]

# These call Go code from couFuncs within courier/scripts.go.
# Scripting is for advanced users and is thus "gatekept" by you having to
# recompile.

Start = ''
Quit = ''
