Header = "House User Interface - Demo Config\n"

[Pager]
Title = 'HUI - Feedback'

[Keys]
Execute = "L"

[Entry]
Alignment = "left"
MenuPrefix = "> ["
MenuPostfix = "]"
ShellPrefix = "> "
ShellPostfix = ""
ShellSessionPrefix = "> <"
ShellSessionPostfix = ">"
GoPrefix = "> !"
GoPostfix = ""

[Entry.Fg]
Active = true
R = 255
G = 255
B = 255

[Entry.Bg]
Active = false
R = 0
G = 0
B = 0

[Entry.HoverFg]
Active = true
R = 0
G = 0
B = 0

[Entry.HoverBg]
Active = true
R = 255
G = 255
B = 255

[Events]
Start = ''
Quit = ''

[Menus]
[Menus.main]
Title = "Main Menu\n---------"

[[Menus.main.Entries]]
Caption = 'whoami'
Shell = 'echo "$USER"'

[[Menus.main.Entries]]
Caption = 'Take notes in "~/temp"'
ShellSession = 'vi "$HOME/temp"'

[[Menus.main.Entries]]
Caption = 'Device'
Menu = 'device'

[Menus.device]
Title = "Device\n------"

[[Menus.device.Entries]]
Caption = 'Show device info'
Shell = 'neofetch --off --color_blocks off'

[[Menus.device.Entries]]
Caption = 'Show hostname'
Shell = 'hostname'

[[Menus.device.Entries]]
Caption = 'Logout'
Go = 'Quit'

[[Menus.device.Entries]]
Caption = 'Suspend'
Shell = 'suspend'

[[Menus.device.Entries]]
Caption = 'Poweroff'
Shell = 'poweroff'

[[Menus.device.Entries]]
Caption = 'Reboot'
Shell = 'reboot'
