Header = "House User Interface - Demo Config\n"

[Pager]
Title = 'HUI - Feedback'

[Keys]
Execute = "L"

[Entry]
Alignment = "left"
MenuPrefix = "> ["
MenuPostfix = "]"
MenuHoverPrefix = "-> ["
MenuHoverPostfix = "]"
ShellPrefix = "> "
ShellPostfix = ""
ShellHoverPrefix = "-> "
ShellHoverPostfix = ""
ShellSessionPrefix = "> <"
ShellSessionPostfix = ">"
ShellSessionHoverPrefix = "-> <"
ShellSessionHoverPostfix = ">"
GoPrefix = "> !"
GoPostfix = ""
GoHoverPrefix = "-> !"
GoHoverPostfix = ""

[Entry.Fg]
Active = true
R = 255
G = 255
B = 255

[Entry.Bg]
Active = false
R = 0
G = 0
B = 0

[Entry.HoverFg]
Active = true
R = 0
G = 0
B = 0

[Entry.HoverBg]
Active = true
R = 255
G = 255
B = 255

[Events]

# These call Go code from huiFuncs within hui/scripts.go.
# Scripting is for advanced users and is thus "gatekept" by you having to
# recompile.

Start = ''
Quit = ''

[Menus]

# Every entry has a Caption and just ONE of the following:
# Menu, Shell, ShellSession, Go.
# Shell and ShellSession differ in that ShellSession is used for commands that
# run in their own mainloop with their own interactive stdin.
# Go calls code from huiFuncs within hui/scripts.go.

[Menus.main]
Title = "Main Menu\n---------"

[[Menus.main.Entries]]
Caption = 'whoami'
Shell = 'echo "$USER"'

[[Menus.main.Entries]]
Caption = 'Take notes in "~/temp"'
ShellSession = 'vi "$HOME/temp"'

[[Menus.main.Entries]]
Caption = 'Device'
Menu = 'device'

[Menus.device]
Title = "Device\n------"

[[Menus.device.Entries]]
Caption = 'Show device info'
Shell = 'neofetch --off --color_blocks off'

[[Menus.device.Entries]]
Caption = 'Show hostname'
Shell = 'hostname'

[[Menus.device.Entries]]
Caption = 'Logout'
Go = 'Quit'

[[Menus.device.Entries]]
Caption = 'Suspend'
Shell = 'suspend'

[[Menus.device.Entries]]
Caption = 'Poweroff'
Shell = 'poweroff'

[[Menus.device.Entries]]
Caption = 'Reboot'
Shell = 'reboot'
